apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: caddyai-base

resources:
  - namespace.yaml
  - rbac.yaml
  - secrets.yaml
  - configmap.yaml
  - pvc.yaml
  - api-deployment.yaml
  - voice-deployment.yaml
  - services.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: caddyai
  app.kubernetes.io/version: v1.0.0

images:
  - name: caddyai
    newTag: IMAGE_TAG
  - name: caddyai-voice
    newTag: IMAGE_TAG

replicas:
  - name: caddyai-api
    count: 2
  - name: caddyai-voice
    count: 1