apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddyai-models-pvc
  labels:
    app.kubernetes.io/name: caddyai
    app.kubernetes.io/component: models-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 50Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
  labels:
    app.kubernetes.io/name: caddyai
    app.kubernetes.io/component: storage-class
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-placeholder
  directoryPerms: "0755"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/caddyai-models"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddyai-logs-pvc
  labels:
    app.kubernetes.io/name: caddyai
    app.kubernetes.io/component: logs-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-sc
  resources:
    requests:
      storage: 10Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-sc
  labels:
    app.kubernetes.io/name: caddyai
    app.kubernetes.io/component: gp3-storage
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  encrypted: "true"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer