apiVersion: v1
kind: Secret
metadata:
  name: caddyai-secrets
  labels:
    app.kubernetes.io/name: caddyai
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  database-url: "postgresql://placeholder:placeholder@placeholder:5432/placeholder"
  redis-url: "redis://placeholder:6379"
  jwt-secret: "placeholder-jwt-secret-key"
  openai-api-key: "placeholder-openai-key"
  aws-access-key-id: "placeholder-aws-access-key"
  aws-secret-access-key: "placeholder-aws-secret-key"
---
apiVersion: v1
kind: Secret
metadata:
  name: caddyai-registry-secret
  labels:
    app.kubernetes.io/name: caddyai
    app.kubernetes.io/component: registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: placeholder-docker-config-json