apiVersion: v1
kind: Service
metadata:
  name: caddyai-api
  labels:
    app: caddyai-api
    app.kubernetes.io/name: caddyai
    app.kubernetes.io/component: api-service
spec:
  selector:
    app: caddyai-api
  ports:
  - name: http
    port: 80
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: caddyai-voice
  labels:
    app: caddyai-voice
    app.kubernetes.io/name: caddyai
    app.kubernetes.io/component: voice-service
spec:
  selector:
    app: caddyai-voice
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: caddyai-api-external
  labels:
    app: caddyai-api
    app.kubernetes.io/name: caddyai
    app.kubernetes.io/component: api-external-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  selector:
    app: caddyai-api
  ports:
  - name: http
    port: 80
    targetPort: 3001
    protocol: TCP
  - name: https
    port: 443
    targetPort: 3001
    protocol: TCP
  type: LoadBalancer